### ISSUE TITLE
Unity build target is broken.

### ISSUE THREAD

**Issue by aggsol** [aaubry/YamlDotNet#132]
Example:

Error	1	The type 'System.Func<T1,T2,TResult>' exists in both 'c:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll' and 'c:\Windows\assembly\GAC_MSIL\System.Core\3.5.0.0__b77a5c561934e089\System.Core.dll'	C:\Users\KDH_admin\sketchbook\YamlDotNet\YamlDotNet\Serialization\INodeDeserializer.cs	29	59	YamlDotNet

It shouldn't reference anything from v4.0. for Unity but I cannot delete the .Net reference. What can I do about it?

**Comment by aggsol** [comment]
Also even the latest succesful build on https://ci.appveyor.com/project/aaubry/yamldotnet/build/3.6.0.89
does not build Unity anymore,

**Comment by aaubry** [comment]
That error should not happen. I will attempt to reproduce it and get back to you. Regarding AppVeyor, it has not yet been configured to build for Unity. I will try to update the build configuration to ensure that the build runs.

**Comment by aaubry** [comment]
That error happens because you did not install the [Visual Studio Tools for Unity](https://visualstudiogallery.msdn.microsoft.com/20b80b8c-659b-45ef-96c1-437828fe7cf2/file/92287/8/Visual%20Studio%202013%20Tools%20for%20Unity.msi). I have updated the build script to install the tools and build the Unity target and the [build succeeds](https://ci.appveyor.com/project/aaubry/yamldotnet/build/3.6.0.101).
