### ISSUE TITLE
CoreClr

### ISSUE THREAD

**Issue by Jetski5822** [aaubry/YamlDotNet#138]
Are you going to look at making this run for CoreCLR?

**Comment by aaubry** [comment]
I will definitely do that, but I don't know when I will have time for it. If you or somebody else wants to do it, that would be great.

**Comment by roji** [comment]
+1 for this

**Comment by Jetski5822** [comment]
I think this lib is already CoreCLR compliant btw :)

HEre is my implementation : https://github.com/OrchardCMS/Brochard/tree/master/src/Orchard.Parser.Yaml

**Comment by aaubry** [comment]
It seems that the library is already compliant with CoreCLR, because the "Profile259" target is compatible with it. I only needed to make [some changes to the nuspec files](https://github.com/aaubry/YamlDotNet/commit/2da9ab86f4b65a3dc19e5aeb9998342edac082f6).
I have added a [minimal sample](https://github.com/aaubry/YamlDotNet/tree/master/samples/dotnet) that proves that it is possible to use YamlDotNet on CoreCLR.

Did I miss anything?

**Comment by aaubry** [comment]
Closing due to lack of feedback.
