### ISSUE TITLE
Call to `MoveNext()` in constructor for EventReader?

### ISSUE THREAD

**Issue by evan-erdos** [aaubry/YamlDotNet#149]
I was trying to get a `IYamlTypeConverter` working, and I couldn't figure out why it was giving me the next scalar after the one I wanted. Following an example I found:

    public object ReadYaml(IParser parser, Type type) {
        var current = parser.Current; // my tagged regex literal, e.g., the thing I actually
        var reader = new EventReader(parser); // wanted to change the type of
        var next = reader.Allow<Scalar>(); // whatever the next node is
    }

For reference, here's the constructor for `EventReader`:

    public EventReader(IParser parser)
    {
        this.parser = parser;
        MoveNext();
    }

Should this happen? Why would the `EventReader` want to skip the current node? I understand that `Allow` has a `MoveNext()` call, but I imagine it's supposed to. The current behavior of `EventReader` advances the parser just by creating it, AFAICT.

**Comment by iasEnvy** [comment]
The example I gave above doesn't even have to use `reader.Allow`, if you print `parser.Current` after creating the `EventReader`, it appears to be the next node.

**Comment by aaubry** [comment]
Well, this is clearly a design flaw in the EventReader. A constructor should not have side effects like this. I'll see what can be done to fix that.

**Comment by iasEnvy** [comment]
Does `EventReader` have to advance the parser for it to function properly? It appears to use `MoveNext` to check if it's at the end of the stream, probably to make sure something bad doesn't happen.

Given that I was able to get what I needed without an `EventReader`, I haven't looked into this much more. The fix might be as simple as removing the initial call to `MoveNext`, but since I haven't looked through all the adjacent classes, I wouldn't know if that would introduce bugs elsewhere.

**Comment by joaope** [comment]
Hi,

I'm trying to bump this issue up because it's actually blocking me from using the lib, at all.

I tried to fix it myself but as a design flaw it requires a bit more in-depth knowledge about the architecture itself, which I obviously don't have right now, ending up fixing on one side and creating ten new problems somewhere else. Removing `MoveNext` obviously won't fix the problem because the all flow depends on that specific call which is moving the parser one step up. I might spend some time on it if someone point me on the right direction...?

Tbh this is probably something very simple to fix by someone with more knowledge about it.

This To say that this is actually blocking me from using the lib because I've tons of edge cases on my yml files and this renders useless `IYamlTypeConverter.ReadYaml` as it needs an `EvenReader` to do something meaningful there. Unless there's a workaround for it (@evan-erdos was saying he has able to dodge the use of the reader)?

**Comment by aaubry** [comment]
Hi,

I agree that it is a flaw that `EventReader` calls `MoveNext`. I checked the code and, excluding tests, the constructor is used only in two places. It should be simple to move the call to `MoveNext` to the code that uses `EventReader` instead. The only problem is that this will break existing code, from users of YamlDotNet, that relies on the `EventReader` class. Given its flaws, I am not sure that anyone actually relies on it, but still that's a possible annoyance.

If we want to avoid the breaking change, we can introduce a new class and mark `EventReader` as obsolete, but I am not sure it is worth it.

What do you think?

**Comment by evan-erdos** [comment]
Fixing this won't break peoples' code, because if they were relying on this in the first place it probably started out broken.
If someone has their heart set on skipping the first node, they can call `MoveNext` themselves. 
I'd add a thing about "help stuff broke when I changed versions" to the FAQ and call it a day.

**Comment by aaubry** [comment]
A quick fix could be like this: #203. If the parser is somewhere in the middle of a stream, do not call `MoveNext`, but still call it at the beginning of the stream.
I am not totally satisfied with this change, because the constructor still does work on some cases, but it has the advantage of not requiring architectural changes while letting the `EventReader` be used in other cases.
What do you think?

**Comment by evan-erdos** [comment]
I feel like that defies programmer expectation even more, by only sometimes causing side effects.

**Comment by joaope** [comment]
> I checked the code and, excluding tests, the constructor is used only in two places. It should be simple to move the call to MoveNext to the code that uses EventReader instead.

This is exactly the path I was taking with the fix, bringing `MoveNext` closer to the Parser. It actually fixes the issue but it will obviously create new ones that you've solve as well, as many flows are expecting that call to happen. And the tests of course. To be honest I think this is probably the hardest and longest path to go with but at the end you'll have better architecture as a all.

If it introduces breaking changes? Yes, it does. And people have to deal with it! They can either choose not to upgrade the library to newest version or they can upgrade it and fix `EventReader` usage. I'm sure many people will appreciate to have the bug fixed :) me and @evan-erdos, for example!

**Comment by aaubry** [comment]
I propose another fix, which is to get rid of `EventReader`. It does not offer much functionality, and equivalent functionality can be implemented as extension methods for `IParser`. This removes the design flaws of `EventReader`, and when you have an `IParser`, you don't need to wrap it inside another object to be able to use it effectively. Please take a look at #203 and let me know what you think. Thanks.

**Comment by aaubry** [comment]
Fixed.
