### ISSUE TITLE
Unorthodox versioning

### ISSUE THREAD

**Issue by dannypike** [aaubry/YamlDotNet#172]
Hello and thank you for a great library! I do have one major problem with using the latest version, though.

I have a number of build tools that cannot handle the format that you use for your released version numbers. I have been told that these tools expect up to four numbers separated by dots and that they fail when they encounter the string "3.8.0-pre212" as a nupkg version number. Would it be possible for you to swap to using dot-delimited numbers only, e.g. "3.8.0.212"?

Dan

**Comment by aaubry** [comment]
Hello,

The version that you mention is from a pre-release package, and the naming follows NuGet's guidelines. You should probably not be using those packages, as they are may be unstable. The stable packages use semantic versioning, so the version numbers have only three components.

**Comment by masaeedu** [comment]
@aaubry Using `pre` is fine, but you're using e.g. "3.9.0-pre268" to denote a build that *succeeds* the "3.9.0" final release, wherease "3.9.0-foo" is supposed to be an unstable *predecessor* of "3.9.0". With the numbering scheme you're following, 3.9.0-pre268 is actually a prerelease candidate for a non-3.9 release (3.10.0 or 4.0.0, depending on the scope of changes). You should fix this, since it violates semver and confuses nuget clients.

**Comment by aaubry** [comment]
That makes sense. I did not notice this problem, but I agree that it needs to be fixed. Thanks for reporting it.

**Comment by aaubry** [comment]
I have made changes to the versioning strategy. When building a pre-release version, the PATCH version will be incremented, relative to the previously released version. This should fix the issue, but please let me know if there is a flaw.
