### ISSUE TITLE
Make property required

### ISSUE THREAD

**Issue by Keraxel** [aaubry/YamlDotNet#202]
Hi!
I'm trying to make property required for parser. For example:
```
[System.ComponentModel.DataAnnotations.Required]
public SiteConfiguration Site { get; set; }
```
should make parser fail if _Site_ is not present inside document.

Is that possible in some way?

**Comment by aaubry** [comment]
There is a fiddle that explains how to achieve that: https://dotnetfiddle.net/90XZmu

**Comment by dug9000** [comment]
This seems unnecessarily complicated. Why not just add something like YamlRequired? Newtonsoft Json has JsonRequired.

**Comment by aaubry** [comment]
Adding something like YamlRequired would solve this specific use-case of making a property mandatory, but proper validation is more than just checking that a property is specified. Adding a complete validation solution is outside of the scope of this library as each application has its own requirements. The design aims to make it easy to plug your own validation if needed.

Regarding the null, it is true that the code should first check that the value is not null. If one of the deserialized objects is null, this code will probably fail.

**Comment by dug9000** [comment]
I think adding YamlRequired would still be very valuable even if it's not a full validation solution because it's something that can't be validated after reading in the Yaml, while just about everything else could be validated after reading the yaml rather than having to override the node object deserializer (at least as long as you don't care about location information in the error message).

I think it's much simpler and pretty common to just do required/optional validation at the Yaml/Json deserialization pass, and do the more complex validation in a separate pass over the already deserialized data. Especially if the validation is complex and requires looking at multiple parts of the data structure at once to determine if it's valid. In such use cases, all that's needed from the deserializer is giving errors for missing required items and unexpected items that don't exist in the deserialized class (already supported by YamlDotNet). Please consider adding YamlRequired or something similar to avoid such users having to add this extra complexity (also the way the error is reported with this approach isn't so great either, it's reported as the InnerException of the YamlException, so you have to dig into the InnerException for the error when trying to catch and report it to the end user).

**Comment by rcdailey** [comment]
I agree with @dug9000 on this one. The developer response to this request is admittedly a little frustrating, as it feels like I am being forced to agree to his design philosophies. Why should I have to write a significant amount of boilerplate code just to get this functionality? Issue #488 also requests similar behavior and @aaubry even links to a [sample solution](https://github.com/aaubry/YamlDotNet/wiki/Samples.ValidatingDuringDeserialization) to this problem. Why can't this just be integrated?

Users that prefer the developer's solution to this problem aren't obligated to use the new attributes. This just makes the library more flexible for others. I feel like doing validation in phases is a good approach, and having YamlDotNet guarantee to me that certain properties are always there helps simplify future validation logic and also doesn't force me to pollute my DTO's with nullable reference syntax.

In any case, consider this my upvote for a built in solution here.

**Comment by rcdailey** [comment]
For anyone looking at a solution to this, here is what I came up with.

Based on the sample that @aaubry provided, which seems to be out of date, I came up with the modified version below. The main changes are that I added proper exception handling to convert the validation exception to a `YamlException` to provide line information with the validation error. This will help users track down where to make edits/corrections in their YAML. I also made the deserializer implement the required interface.

```cs
public class ValidatingDeserializer : INodeDeserializer
{
    private readonly INodeDeserializer _nodeDeserializer;

    public ValidatingDeserializer(INodeDeserializer nodeDeserializer)
    {
        _nodeDeserializer = nodeDeserializer;
    }

    public bool Deserialize(IParser parser, Type expectedType,
        Func<IParser, Type, object?> nestedObjectDeserializer, out object? value)
    {
        if (!_nodeDeserializer.Deserialize(parser, expectedType, nestedObjectDeserializer, out value) ||
            value == null)
        {
            return false;
        }

        var context = new ValidationContext(value, null, null);

        try
        {
            Validator.ValidateObject(value, context, true);
        }
        catch (ValidationException e)
        {
            if (parser.Current == null)
            {
                throw;
            }

            throw new YamlException(parser.Current.Start, parser.Current.End, e.Message);
        }

        return true;
    }
}
```

I also added a convenient extension method for attaching this to the builder:

```cs
public static class YamlDotNetExtensions
{
    public static DeserializerBuilder WithRequiredPropertyValidation(this DeserializerBuilder builder)
    {
        return builder
            .WithNodeDeserializer(inner => new ValidatingDeserializer(inner),
                s => s.InsteadOf<ObjectNodeDeserializer>());
    }
}
```

And finally using it in my actual code. Attaching it to the builder:

```cs
_deserializer = new DeserializerBuilder()
    .WithRequiredPropertyValidation()
    .Build();
```

And the attribute being specified on one of my DTOs:

```cs
public class QualityProfileConfig
{
    [Required]
    public string Name { get; set; } = "";
    public int Score { get; set; }
}
```

As I already mentioned I find most of this unnecessary for users to do. There's enough code duplication across projects that I think this should be made into a built in feature. But it's a one time setup for me, so I can't complain too hard. I just hope that the developer will reconsider.
