### ISSUE TITLE
filter property when serialize

### ISSUE THREAD

**Issue by KiritoStudio** [aaubry/YamlDotNet#217]
Hi, 
I want to serialize an class object(called class A). Class A has a property named Type. I want to use the Type property to filter some non-usage properties or only specify some properties that I want to serialize. I think [YamlIgnore] is not the choise for my case because different Type should filter different properties. Sorry for my pool English.

**Comment by aaubry** [comment]
You should be able to achieve that by registering a custom [`ITypeInspector`](https://github.com/aaubry/YamlDotNet/blob/5d9948940a8cdcb8a1cf2cf77c5b89bf360e8409/YamlDotNet/Serialization/ITypeInspector.cs#L30) using [`DeserializerBuilder.WithTypeInspector`](https://github.com/aaubry/YamlDotNet/blob/5d9948940a8cdcb8a1cf2cf77c5b89bf360e8409/YamlDotNet/Serialization/BuilderSkeleton.cs#L149). You will simply need to check test if the specified type is the one you want to customize, and filter out unwanted properties. Otherwise, just forward to the inner type inspector. Here is a skeleton to get you started:

```C#
public class MyTypeInspector : TypeInspectorSkeleton
{
    private readonly ITypeInspector inner;

    public MyTypeInspector(ITypeInspector inner)
    {
        this.inner = inner;
    }

    public override IEnumerable<IPropertyDescriptor> GetProperties(Type type, object container)
    {
        var properties = inner.GetProperties(type, container);
        if (type == typeof(MyType))
        {
            properties = properties.Where(...);
        }
        return properties;
    }
}
```

Then you can register it like this:

```C#
var serializer = new SerializerBuilder()
    .WithTypeInspector(inner => new MyTypeInspector(inner))
    .Build();
```

Let me know if you need more help.

**Comment by KiritoStudio** [comment]
Nice solution, worked for me. Thanks a lot!
