### ISSUE TITLE
Allow to apply custom converter to properties in YamlDotNet

### ISSUE THREAD

**Issue by aaubry** [aaubry/YamlDotNet#233]
[See discussion here](http://stackoverflow.com/questions/41576410/how-to-apply-custom-converter-to-properties-in-yamldotnet/41580581#41580581)

> I'm porting my configuration file from .json to .yaml format. In Newtonsoft.Json I was able to apply attribute to a property which needed custom converter, for example
> 
> [JsonConverter(typeof(CustomIdConverter))]
> public IList<CustomID> Users { get; set; }
> 
> How would I do the same using YamlDotNet?
> 
> I know converters should implement IYamlTypeConverter interface, but how would I apply this converter to exact property?

**Comment by tistocks** [comment]
I'll also note, that there are times where IYamlConvertible will not suffice because (as in my case) the type is abstract or requires other forms of custom construction. 

However, it asking every user of a model to always remember to use SerializerBuilder and use the WithTypeConverter process is not a good workflow.

Being able to attach the Converter to the class gives the correct use pattern without the need for someone to remember ("oh, I used this model from this library and now have to construct the serializer specially").

**Comment by alexrosenfeld10** [comment]
+1 for this

**Comment by naefp** [comment]
is this planned to be implemented?

**Comment by EdwardCooke** [comment]
This issue appears to be abandoned, I'm going to close it.

**Comment by SchreinerK** [comment]
and where is the solution?

**Comment by glopesdev** [comment]
> and where is the solution?

@SchreinerK In this unit test: https://github.com/aaubry/YamlDotNet/blob/8d1a5cb7f1422da7f915c8ca6fcd3a9511e5af9a/YamlDotNet.Test/Serialization/TypeConverterAttributeTests.cs#L38

Basically you make a `IYamlTypeConverter` that does not accept any type, register it globally (so it can be looked up), and then tag only the properties where you want to use it with `YamlConverterAttribute`.

I didn't find it documented anywhere, and as it is slightly convoluted (you need to both register a global converter which does not accept any type, and tag properties with the attribute), I am leaving it here for future reference.
