### ISSUE TITLE
Load / Modify / Save DOM facilities?

### ISSUE THREAD

**Issue by jskeet** [aaubry/YamlDotNet#247]
I'm in a situation where I want to load a YAML document that I don't have a complete schema for (so I don't want to deserialize to a CLR type model), modify some nodes, then save the document out again - ideally with as few formatting changes as possible, but that's not a big deal.

Browsing around the code, the representation model appears to be publicly immutable - have I missed something, or is this basically a use case YamlDotNet isn't designed for? (Completely understand if so - I just won't try pushing against the flow.)

**Comment by aaubry** [comment]
The model that is exposed by [YamlStream](https://github.com/aaubry/YamlDotNet/blob/master/YamlDotNet/RepresentationModel/YamlStream.cs) is mutable. Maybe you are looking at the lower-level parser events, which are immutable ?

[Here is a sample](https://dotnetfiddle.net/HfI1DC) that loads a document, updates it, then writes it to the console. Basically you need to:

1. Create a new `YamlStream`.
1. Use its `Load` method to load the document / stream.
1. Modify the object model.
1. Store the updated document using the `Save` method.

Note that the `Save` method takes a parameter named `assignAnchors`. Its purpose is to automatically assign anchors to nodes that are the same. In your use case, you want to pass false, since that would introduce unintended changes. That parameter should be deprecated anyways since it has [issues](https://github.com/aaubry/YamlDotNet/issues/248).

**Comment by jskeet** [comment]
Aha - I'd been fooled by `YamlNode` itself having no obvious way to change anything - the fact that subclasses allow for that had escaped me. Sorry for not looking more closely - it looks like this should be fine :)
