### ISSUE TITLE
Support KeyValuePair<,> and KeyValuePair

### ISSUE THREAD

**Issue by edwinvandeburgt** [aaubry/YamlDotNet#249]
Because KeyValuePair only has a public getter for Key, during deserialization the Key property cannot be found, probably somewhere here:

    public override IEnumerable<IPropertyDescriptor> GetProperties(Type type, object container)
    {
        return _innerTypeDescriptor.GetProperties(type, container)
            .Where(p => p.CanWrite);
    }

Deserialization fails now.

Because KeyValuePair is such a base type for .NET (and correctly handled by the DataContractSerializer), I think there should be some special handling for KeyValuePair(<,>).

**Comment by aaubry** [comment]
Do you have a concrete use case for `KeyValuePair` ? Usually they are serialized as part of an `IDictionary`, which already has special handling. Where else do you use `KeyValuePair` ?

**Comment by edwinvandeburgt** [comment]
Actually, we have `List` and `List<KeyValuePair<,>`. Apart from that, it would be nice if we could swap the DataContractSerializer with YamlDotNet without worrying about reduced compatibility...

**Comment by aaubry** [comment]
You can easily [add support for deserializing KeyValuePair by adding a custom `INodeDeserializer`](https://dotnetfiddle.net/f5hUZ3). I am not convinced that this should be built-in, though, because the use cases of serializing KeyValuePair seem rare, and every added feature has a cost even if you do not use it.

Regarding unsupported formats being caught during serialization, that's not really possible because whether you will be able to deserialize an object depends on the configuration of the deserializer. Moreover, there are many cases where you do not care about deserialization because you just want to produce a YAML document.
You can use the [`EnsureRoundtrip`](https://github.com/aaubry/YamlDotNet/blob/master/YamlDotNet/Serialization/SerializerBuilder.cs#L209) method on the serializer builder if you want to be sure that it will be possible to deserialize the document. However, in this case it would succeed, but emit only writable properties, so you would end up with an empty KeyValuePair.

**Comment by edwinvandeburgt** [comment]
Thank you very much for providing a solution!

EnsureRoundtrip sounds like an interesting property; I think it would be nice when EnsureRoundtrip is true, the (de)serializer would be compatible and thus swappable with the DataContractSerializer, or maybe another property could be introduced for this purpose, but I can realize that (optional) conformance to the DataContractSerializer with respect to (de)serializable types wasn't one of your design goal.

Anyway, thanks for making this beautiful library available!

**Comment by ramon-garcia** [comment]
Why don't you place this sample https://dotnetfiddle.net/f5hUZ3 in the samples directory?

**Comment by bardal** [comment]
FYI I have the same use case. I want to maintain order for a list of KeyValuePairs as this ordering is used within a UI. I had started by looking for an OrderedDictionary but as there's no .NET builtin generic version settled on using List<KeyValuePair<,>>.

I'd like to keep the YAML as clean/vanilla as possible and am pretty flexible as to what objects they get deserialised in to. Dictionary is ideal other than not preserving order! Ideally I'd avoid having to add Key:, Value: text into the YAML.
