### ISSUE TITLE
Build failed in appveyor

### ISSUE THREAD

**Issue by mbellet** [aaubry/YamlDotNet#264]
I noticed that the build in https://ci.appveyor.com/project/aaubry/yamldotnet failed.
This is the error that you can read in the site too:
~~~
Cake.exe : An error occurred when executing task 'Set-Build-Version'.
At line:1 char:1
+ & "C:\projects\yamldotnet\tools\Cake\Cake.exe" "build.cake" -target=" ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (An error occurr...Build-Version'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Error: 
UpdateBuildVersion failed (2).
Command executed with exception: 
~~~

**Comment by aaubry** [comment]
This is due to the way the versioning is setup. The version is given by a tag, but pushing the branch and pushing the tag both cause a build. If the tag is pushed before the branch build starts, both builds will see the tag and try to build the same version. I am not sure what to do about this. It is not a big deal, but if there is a fix, I would consider using it.

**Comment by mbellet** [comment]
I saw that there is an option to build tags only: [http://help.appveyor.com/discussions/questions/261-only-deploy-when-theres-a-new-tag](http://help.appveyor.com/discussions/questions/261-only-deploy-when-theres-a-new-tag).
I hope that this can help you.

**Comment by EdwardCooke** [comment]
I think that has been resolved as only one build is running now. It also appears to be an abandoned issue. Closing it.
