### ISSUE TITLE
Parse properties in a Dictionary

### ISSUE THREAD

**Issue by VGBenjamin** [aaubry/YamlDotNet#328]
Hello,

I would like to parse the following YAML
```
urls: 
- who: /fr-fr/who-we-are
- test: /fr-fr/test

targetDirectory: d:\temp\
```

Into the following structure:
```
public class UserConfig
{
    public Dictionary<string, string> Urls { get; set; }
    public string TargetDirectory { get; set; }
}
```

I try to serialize it with:
```
var deserializer = new DeserializerBuilder()
    .WithNamingConvention(new CamelCaseNamingConvention())
    .Build();
```

But I always obtains  the following error: (Line: 2, Col: 1, Idx: 8) - (Line: 2, Col: 2, Idx: 9): Expected 'MappingStart', got 'SequenceStart' (at Line: 2, Col: 1, Idx: 8).

Is this library able to support a mapping of key values? If yes how can I do that?

Regards,
Benjamin V.

**Comment by aaubry** [comment]
That's because your YAML document is a **sequence of mappings**, instead of a **mapping**. That would map to a `List<Dictionary<string, string>>`. If you can control the structure of your YAML document, you should change it to:

```yaml
urls: 
  who: /fr-fr/who-we-are
  test: /fr-fr/test

targetDirectory: d:\temp\
```

otherwise, you will need to implement a class that implements `ICollection<Dictionary<string, string>` and use that type as the Urls property.

**Comment by VGBenjamin** [comment]
Ok it looks a bit strange for me but the solution you provide work great!
Thanks a lot.
