### ISSUE TITLE
YamlStream.Save(TextWriter output) adds lines like "&1944107265"

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [aaubry/YamlDotNet#331]
Please check this repro https://github.com/IlyaFinkelshteyn/YamlDotNetRepro. 

For us (AppVeyor) it leads to unwanted results when people press `Export YAML` button in the UI. It happens intermittently.

**Comment by aaubry** [comment]
You should set the second parameter of the Save method to false. Otherwise, the method will assign anchors automatically so that if the same instance is used later, an alias is used instead of replicating the content.
This will solve your problem, although by looking at your output, it does not seem that the feature is working as intended. I will have to look into that.

**Comment by IlyaFinkelshteyn** [comment]
Thanks a ton!
