### ISSUE TITLE
How to Deserialize YAML with Merge Key and Override Value?

### ISSUE THREAD

**Issue by danstuken** [aaubry/YamlDotNet#388]
(This question is a duplicate of this [SO question](https://stackoverflow.com/questions/54887731/how-to-parse-yaml-with-merge-key-and-override-in-yamldotnet) )

This SO [answer from 2014](https://stackoverflow.com/a/18900623/166707) shows an example of deserializing some YAML with merge keys and and override value. It looks like the YamlDotNet API has evolved since then (I can't find the `EventReader` class for e.g.) so this is the code I've ended up with:

```c#
using System;
using System.IO;
using YamlDotNet.Core;
using YamlDotNet.RepresentationModel;

namespace Dummy.ParseYaml
{
    class Program
    {
        static string DUMMY_YAML = @"---
aliases:
  globals: &globals
    key1: 'value1'
    key2: 'value2'
  contexts:
    context1:
      <<: *globals
    context2:
      key1: 'override'
      <<: *globals
";
        static void Main(string[] args)
        {
            var mergingParser = new MergingParser(new Parser(new StringReader(DUMMY_YAML)));
            var yamlStream = new YamlStream();
            yamlStream.Load(mergingParser);
        }
    }
}
```

But this code throws a `Duplicate Key` error.

How can I deserialize this YAML?

**Comment by aaubry** [comment]
The implementation of merge keys is a bit of a hack. It just "pastes" the content of the referenced node, and there's no logic to override keys. This causes problem when loading with YamlStream because the implementation of YamlMapping disallows duplicate keys. The example on Stack Overflow is using the `Deserializer`, which ignores duplicate keys.

If you really need to use YamlStream to load this document, I'm afraid you won't be able to use merge keys.
