### ISSUE TITLE
Audit the failing tests from official YAML

### ISSUE THREAD

**Issue by aaubry** [aaubry/YamlDotNet#398]
As discussed in #395, audit (address or explain) the following failing tests from official YAML test suite:
- [x] [DK3J](https://github.com/yaml/yaml-test-suite/tree/data/DK3J)
- [x] [6M2F](https://github.com/yaml/yaml-test-suite/tree/data/6M2F)
- [x] [NJ66](https://github.com/yaml/yaml-test-suite/tree/data/NJ66)
- [x] [4MUZ](https://github.com/yaml/yaml-test-suite/tree/data/4MUZ)
- [x] [NHX8](https://github.com/yaml/yaml-test-suite/tree/data/NHX8)
- [x] [WZ62](https://github.com/yaml/yaml-test-suite/tree/data/WZ62)
- [x] [RTP8](https://github.com/yaml/yaml-test-suite/tree/data/RTP8)
- [x] [W5VH](https://github.com/yaml/yaml-test-suite/tree/data/W5VH)
- [x] [27NA](https://github.com/yaml/yaml-test-suite/tree/data/27NA)
- [x] [UDM2](https://github.com/yaml/yaml-test-suite/tree/data/UDM2)
- [x] [8XYN](https://github.com/yaml/yaml-test-suite/tree/data/8XYN)
- [x] [4ABK](https://github.com/yaml/yaml-test-suite/tree/data/4ABK)
- [x] [KZN9](https://github.com/yaml/yaml-test-suite/tree/data/KZN9)
- [x] [Q5MG](https://github.com/yaml/yaml-test-suite/tree/data/Q5MG)
- [x] [Y2GN](https://github.com/yaml/yaml-test-suite/tree/data/Y2GN)
- [x] [2JQS](https://github.com/yaml/yaml-test-suite/tree/data/2JQS)
- [x] [S3PD](https://github.com/yaml/yaml-test-suite/tree/data/S3PD)
- [x] [R4YG](https://github.com/yaml/yaml-test-suite/tree/data/R4YG)
- [x] [9SA2](https://github.com/yaml/yaml-test-suite/tree/data/9SA2)
- [x] [UT92](https://github.com/yaml/yaml-test-suite/tree/data/UT92)
- [x] [HWV9](https://github.com/yaml/yaml-test-suite/tree/data/HWV9)
- [x] [6ZKB](https://github.com/yaml/yaml-test-suite/tree/data/6ZKB)
- [x] [9MMW](https://github.com/yaml/yaml-test-suite/tree/data/9MMW)
- [x] [6BCT](https://github.com/yaml/yaml-test-suite/tree/data/6BCT)
- [x] [W4TN](https://github.com/yaml/yaml-test-suite/tree/data/W4TN)
- [x] [S4JQ](https://github.com/yaml/yaml-test-suite/tree/data/S4JQ)
- [x] [K3WX](https://github.com/yaml/yaml-test-suite/tree/data/K3WX)
- [x] [8MK2](https://github.com/yaml/yaml-test-suite/tree/data/8MK2)
- [x] [52DL](https://github.com/yaml/yaml-test-suite/tree/data/52DL)
- [x] [2SXE](https://github.com/yaml/yaml-test-suite/tree/data/2SXE)
- [x] [FP8R](https://github.com/yaml/yaml-test-suite/tree/data/FP8R)
- [x] [9DXL](https://github.com/yaml/yaml-test-suite/tree/data/9DXL)
- [x] [FRK4](https://github.com/yaml/yaml-test-suite/tree/data/FRK4)
- [x] [2LFX](https://github.com/yaml/yaml-test-suite/tree/data/2LFX)
- [x] [7Z25](https://github.com/yaml/yaml-test-suite/tree/data/7Z25)
- [x] [3UYS](https://github.com/yaml/yaml-test-suite/tree/data/3UYS)
- [x] [QT73](https://github.com/yaml/yaml-test-suite/tree/data/QT73)
- [x] [A2M4](https://github.com/yaml/yaml-test-suite/tree/data/A2M4)
- [x] [6LVF](https://github.com/yaml/yaml-test-suite/tree/data/6LVF)
- [x] [DBG4](https://github.com/yaml/yaml-test-suite/tree/data/DBG4)
- [x] [M7A3](https://github.com/yaml/yaml-test-suite/tree/data/M7A3)
- [x] [BEC7](https://github.com/yaml/yaml-test-suite/tree/data/BEC7)
- [x] [5MUD](https://github.com/yaml/yaml-test-suite/tree/data/5MUD)

**Comment by am11** [comment]
There is also a subset of seven tests, where parser is not failing as expected by the spec:
https://github.com/aaubry/YamlDotNet/blob/f147c4a8f17ffc54a8526ea56bd0004156e2ad13/YamlDotNet.Test/Spec/SpecTests.cs#L75-L82

**Comment by am11** [comment]
Just for clarity: this issue only covers parsing (parser and scanner) and not the output emission (emitter and serializer). Once parsing is 100% complaint with the spec, we can focus on emission part afterwards (already gotten some insights from YAML spec folks).

Few updates for this issue:

1. All cases in the first comment are addressed and nuget package v6.1.2 has been released. @aaubry, please check the boxes (or replace `- [ ]` with `- [x]` in the markdown. 😸
2. The fix for false-positive cases from comment 2 (now eight instead of seven) are underway, once those are fixed, IMO we can mention it in the README that YDN's parsing is YAML v1.2 complaint.
3. There are 20 exactness issues highlighted in #422 in case of error.

I have managed to address 10 cases of `3.` and all cases of `2.`; will first complete the full patch (covering all cases of `2` and `3`, then split it into commits).

**Comment by am11** [comment]
- [ ] `S98Z` is now an error. see https://github.com/yaml/yaml-test-suite/issues/37.
