### ISSUE TITLE
YamlFrontmatter in Markdown File

### ISSUE THREAD

**Issue by mdmoura** [aaubry/YamlDotNet#432]
I have a Markdown document with YAML data and Markdown content:

```
---
title: Welcome post
tags: [tech]
enabled: true
---

This is the post markdown body.
```

And I have a class model:

    public class PostModel {
      public String Title { get; set; }
      public String[] Tags { get; set; }
      public Boolean Enabled { get; set; }
      public String Body { get; set; }
    }

Is it possible to fill the PostModel properties with the content of the YAML file?

Body is the text after the second `---`. The remaining properties are the YAML FrontMatter

**Comment by aaubry** [comment]
Sure, it is possible, but it requires some extra work. Since the start of the document is actually a valid YAML stream, it can be parsed without problems. The deserializer won't accept the file as-is because it expects a stream (file) containing a single document, but you can work around this by using an `IValueDeserializer` instead, which is the component that parses the document's content.

I put together a [working sample that you can check here](https://dotnetfiddle.net/P4p68y). The code looks like this:

```c#
// Configure a deserializer
var deserializer = new DeserializerBuilder()
	.WithNamingConvention(new CamelCaseNamingConvention())
			
	// Because the stream will contain other stuff besides the initial YAML document,
	// we need to use an IValueDeserializer
	// which provides lower-level deserialization facilities.
	.BuildValueDeserializer();

var parser = new Parser(input);
		
// Consume the initial parser events
parser.Expect<StreamStart>();
parser.Expect<DocumentStart>();

// Use the deserializer to parse the YAML document
var model = (PostModel)deserializer.DeserializeValue(parser, typeof(PostModel), new SerializerState(), deserializer);
		
// Read the body "manually"
model.Body = input.ReadToEnd();
```

If you want to write the model to a file, that [can also be done quite easily](https://dotnetfiddle.net/tJUeDN):

```c#
var serializer = new SerializerBuilder()
	.WithNamingConvention(new CamelCaseNamingConvention())      // Camel-case property names
	.WithEventEmitter(next => new UseFlowStyleSequences(next))  // Use flow style for sequences (see https://github.com/aaubry/YamlDotNet/wiki/Serialization.Serializer#witheventemitter)
	.Build();
		
output.WriteLine("---");
		
// Use the serializer to emit the YAML part
serializer.Serialize(output, model);
		
output.WriteLine("---");

// Write the body "manually"
output.WriteLine(model.Body);
```

**Comment by aaubry** [comment]
I will close this issue as there has been no feedback. Feel free to reopen it if necessary.

**Comment by perlun** [comment]
@aaubry Old issue, but I am currently trying this approach out in my project. However, it seems like I am running into some really odd off-by-one error.

The first character in the body gets "chopped off" so that `model.Body` in your example becomes `his is the post markdown body.`

Here is my sample program:

```c#
            // This would be our input file
            TextReader input = new StringReader(@"---
title: Welcome post
tags: [tech]
enabled: true
---
This is the post markdown body.");

            // Configure a deserializer
            var deserializer = new DeserializerBuilder()
                .WithNamingConvention(UnderscoredNamingConvention.Instance)

                // Because the stream will contain other stuff besides the initial YAML document,
                // we need to use an IValueDeserializer
                // which provides lower-level deserialization facilities.
                .BuildValueDeserializer();

            var parser = new Parser(input);

            // Consume the initial parser events
            parser.Consume<StreamStart>();
            parser.Consume<DocumentStart>();

            // Use the deserializer to parse the YAML document
            var model = (PostModel) deserializer.DeserializeValue(parser, typeof(PostModel), new SerializerState(),
                deserializer);

            // Read the body "manually"
            model.Body = input.ReadToEnd();

            // Outputs "his is the post markdown body" instead of "This is the post markdown body"
            Console.WriteLine(model.Body);
```

Here is the full example: https://dotnetfiddle.net/xAAK4H

Any ideas what could be causing this?

**Comment by aaubry** [comment]
This is because the parser is not guaranteed to not read more characters than necessary. The parser uses an internal buffer that contains up to 8 unprocessed characters, therefore it is likely that this will happen. I'm afraid that you will need to preprocess the file before parsing each part.

**Comment by perlun** [comment]
@aaubry Alright, thanks. Not much to do about that then I guess. I was hoping for the tool to be able to help me, but OTOH splitting the file on `---` + newline and putting the pieces together isn't really rocker science. :wink: Thanks anyway!
