### ISSUE TITLE
Quotes are automatically ignored

### ISSUE THREAD

**Issue by brutalsatyr** [aaubry/YamlDotNet#434]
Hi, 

I'm writing a tool to transform yaml files using this framework. For this I don't know the structure of the yaml files beforehand, so I have to deserialize it to a dictionary<object, object>

When deserializing the yaml file, it completely ignores the quotes around it. So when serializing the transformed object back to a yaml file , there are no quotes to be seen. Which broke my yaml file. 

At the moment I'm working around this with a custom typeConvertor for the deserializer that adds the quotes to the parsed value.

```
 public object ReadYaml(IParser parser, Type type)
        {
            object value;
            Scalar scalar = (Scalar) parser.Current;

            if (scalar.Style == ScalarStyle.DoubleQuoted)
            {
                value = scalar.Value.Surround('\"');
            }
            else if (scalar.Style == ScalarStyle.SingleQuoted)
            {
                value = scalar.Value.Surround('\'');
            }
            else
            {
                value = scalar.Value;
            }

            parser.MoveNext();
            return value;
        }`
```

After this, I can serialize it back to yaml with a custom EventEmmiter that replaces the TypeAssigningEventEmitter

```
//TypeAssigningEventEmitter

case TypeCode.String:
case TypeCode.Char:
      eventInfo.Tag = "tag:yaml.org,2002:str";
      if (eventInfo.Source.Value.ToString().StartsWith("\""))
      {
         eventInfo.RenderedValue = eventInfo.Source.Value.ToString().Replace("\"", "");
         eventInfo.Style = ScalarStyle.DoubleQuoted;
      }
      else if (eventInfo.Source.Value.ToString().StartsWith("\'"))
      {
         eventInfo.RenderedValue = eventInfo.Source.Value.ToString().Replace("\'", "");
         eventInfo.Style = ScalarStyle.SingleQuoted;
     }
     else
     {
          eventInfo.RenderedValue = eventInfo.Source.Value.ToString();
          suggestedStyle = ScalarStyle.Any;
     }
     break;`

//TypeAssigningEventEmitter

```

However this seems like a patchwork solution and I was wondering why this design choice was made to not include the quotes?

**Comment by aaubry** [comment]
Quoted strings are part of the YAML specification. If you need to represent a value that actually contains quotes, you need to escape them. See the following example:

```yaml
- "hello"
- hello
- 'hello'
```

In the above example, all three strings contain the same text - `hello` - but use different styles. The equivalent in JSON would be:

```json
[
  "hello",
  "hello",
  "hello"
]
```

If you need to represent a string that contains quotes, you need to escape them, enclose the quotes in a different type of quotes, or use the block scalar syntax:

```yaml
- "\"hello\""
- '"hello"'
- "'hello'"
- '''hello'''
- |
  "hello"
```

In the above example, each string contains either `"hello"` or `'hello'`. The equivalent in JSON would be:

```json
[
  "\"hello\"", 
  "\"hello\"", 
  "'hello'", 
  "'hello'", 
  "\"hello\""
]
```

When writing the document, the quotes are selected depending on the content. The play style is preferred as it tends to help readability. You can force the double quotes, as you did, but since they a presentation detail, you should not interfere with them.

I suggest that you refer to the [YAML specification](https://yaml.org/spec/1.2/spec.html#id2786942) for more details about quoted scalars.

**Comment by aaubry** [comment]
You can also try the examples that I provided in this [Online YAML Parser](https://yaml-online-parser.appspot.com/).

**Comment by aaubry** [comment]
I will close this issue as there has been no feedback. Feel free to reopen it if necessary.
