### ISSUE TITLE
DefaultValue is ignored in Deserializer

### ISSUE THREAD

**Issue by Vladimir35** [aaubry/YamlDotNet#465]
I provide a "default" true value via the DefaultValue attribute, but the deserializer ignores this property leaving false. Is it by design and should i write a custom deserializer for that?

Sample-Code: https://dotnetfiddle.net/hJ2NFd

    public class Order
    {
        [DefaultValue(true)]
        public bool DoubleCheckThis { get; set; }
    }

This is a "copy" of tickets:
https://github.com/aaubry/YamlDotNet/issues/124
https://github.com/aaubry/YamlDotNet/issues/300

**Comment by aaubry** [comment]
The `DefaultValue` attribute indicates which value is the default, but is is your responsibility to initialize the property to that value in the class' constructor:

```c#
public class Order
{
    [DefaultValue(true)]
    public bool DoubleCheckThis { get; set; } = true;
}
```

I feel that this is the correct behavior and I've checked other serializers, namely `DataContractSerializer` (.NET framework) and `JsonSerializer` (Json.NET), and none of them attempts to initialize the property with the value indicated in the attribute.

Note that since `DefaultValue` is an attribute, you would not be able to state the default value for complex types, so using it to initialize a property would not be a general solution.

Now if you really want this behavior, it is possible to implement it yourself. One way is to register an implementation of the [`IObjectFactory` interface](https://github.com/aaubry/YamlDotNet/wiki/Serialization.Deserializer#withobjectfactoryiobjectfactory) that checks each property and initializes it with the content of the `DefaultValue` attribute, if present.
