### ISSUE TITLE
Sequence Mapping on Save ignore spaces

### ISSUE THREAD

**Issue by flowdopip** [aaubry/YamlDotNet#538]
Example

I read the follow example
maintainers:
  - john.doe
  - john.smith
and when i use YamlStream.Load and after that without changing anything i do a Stream.Save( , false) i get the following result:
maintainers:
- john.doe
- john.smith

When i use the function save, the code removes the empty spaces.

**Comment by EdwardCooke** [comment]
When the YAML is deserialized (turned from YAML to an object) the whitespace (and comments) will be removed when re-serialized and will be formatted to the yaml spec. There is some options you can change to tweak the resulting output, however, there's nothing to keep the extra whitespace.

I'm also going to close this issue since it's almost 2 years old.
