### ISSUE TITLE
Question about security implications of deserializing arbitray objects from YAML with yamldotnet

### ISSUE THREAD

**Issue by bt-nia** [aaubry/YamlDotNet#614]
I'm currently evaluating this library from a security perspective. Since YAML can be used to serialize objects, I was wondering if the defaults provided by the parser are set such that deserialization of arbitrary objects is prevented. Putting it differently:

What are the steps needed to allow for the creation of any type of object give a YAML string containing the definition of a specific type? From what I could tell going through the documentation, this behaviour is not easily reproducible, since the deserializer expects a type of an object to populate with the given data.

As a second, related question: Are validation checks that are present during the creation of objects (e.g. "Age" property can not be larger than 130 and smaller than 0) or when using a getter/setter pattern being used when creating the object, or is it possible to create objects that have unexpected data inside them that way?

**Comment by aaubry** [comment]
Since [release 5.0.0](https://github.com/aaubry/YamlDotNet/releases/tag/v5.0.0), YamlDotNet does not load arbitrary types by default. In order to make a type accessible, you need to register it explicitly, as explained in those release notes. In order to allow creating any type of object, one needs to enables it explicitly by registering the `TypeNameInTagNodeTypeResolver` class, or a similar custom implementation.

Regarding your second question, YamlDotNet calls the setters of the properties, so any validation that is performed by the setters will be executed as normal.

**Comment by bt-nia** [comment]
@aaubry thank you so much for the answer. That clears up my concerns. I'll keep this in mind and inform our devs accordingly. Cheers!
