### ISSUE TITLE
When I upgraed the YamlDotNet from 4.2.1 to 11.2.1, I met an error

### ISSUE THREAD

**Issue by cysnet** [aaubry/YamlDotNet#633]
When I upgraed the YamlDotNet from 4.2.1 to 11.2.1, I met an error:
`Could not load file or assembly 'YamlDotNet, Version=4.2.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.`

Then I and the bindingRedirect in the web.config file, it still doesn't work. Is there any suggestions?

The bindingRedirect as below:
`		    <dependentAssembly>
                <assemblyIdentity name="YamlDotNet" publicKeyToken="ec19458f3c15af5e" culture="neutral" />
                <bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
            </dependentAssembly>`

**Comment by aaubry** [comment]
This is because you have some code that is using the non-signed version of YamlDotNet (`PublicKeyToken=null`), and it is not possible to redirect from a non-signed assembly to a signed one. All recent versions of YamlDotNet are signed, so you will need to recompile any library that is still using the non-signed version.

Anyway, each major version introduces breaking changes, so it is unlikely that redirecting between version 4.x.x to 11.x.x would work at all. Each major release contains release notes that have information on which breaking changes were introduced. For example, [release 5.0.0](https://github.com/aaubry/YamlDotNet/releases/tag/v5.0.0) removed some legacy syntax that your code may depend on. You should refer to these when upgrading.

**Comment by cysnet** [comment]
> This is because you have some code that is using the non-signed version of YamlDotNet (`PublicKeyToken=null`), and it is not possible to redirect from a non-signed assembly to a signed one. All recent versions of YamlDotNet are signed, so you will need to recompile any library that is still using the non-signed version.
> 
> Anyway, each major version introduces breaking changes, so it is unlikely that redirecting between version 4.x.x to 11.x.x would work at all. Each major release contains release notes that have information on which breaking changes were introduced. For example, [release 5.0.0](https://github.com/aaubry/YamlDotNet/releases/tag/v5.0.0) removed some legacy syntax that your code may depend on. You should refer to these when upgrading.

that is make sence. this issue can be closed

**Comment by aaubry** [comment]
If you need help upgrading, feel free to ask :)
