### ISSUE TITLE
`YamlStream.Load(TextReader)` interprets an empty value as an empty string instead of null. 

### ISSUE THREAD

**Issue by sfwester** [aaubry/YamlDotNet#810]
**Describe the bug**

Version: 13.1.0

According to:
- https://yaml.org/type/null.html
- https://yaml.org/spec/1.2.2/#72-empty-nodes

```yaml
annotations:
```

generally expected to be equivalent to 

```yaml
annotations: ~
```

However, `YamlStream.Load(TextReader)` defaults `annotations` to the empty string. i.e.,

```yaml
annotations: ''
```

**To Reproduce**

```cs
using System;
using System.IO;
using YamlDotNet.RepresentationModel;
					
public class Program
{
	public static void Main()
	{
		var inYaml = "annotations:";

                using var sr = new StringReader(inYaml);

                var yamlStream = new YamlStream();
                yamlStream.Load(sr);

                using var writer = new StringWriter();
                new YamlStream(yamlStream.Documents).Save(writer);
                var outYaml = writer.ToString();
		
		Console.Write(outYaml);
	}
}
```

**Actual**
```
annotations: ''
...

```

**Expected**
```
annotations: ~
...

```
or
```
annotations: null
...

```

**Comment by EdwardCooke** [comment]
Ok, so I finally got some time to look at this. It isn't that it's interpreting it as an empty string, but rather an empty scalar object. This is by design and changing the way it's handled and converting it to a null would be a breaking change that could easily cause a lot of problems for anybody using this.

What it does is reads the yaml node explicitly. Setting the scalar object with an empty string and no tag, since one doesn't exist on that node and marks it as a plain formatted scalar (as opposed to a single, double quoted, etc). Then, when it serializes it, since there is no tag, it writes out a quoted empty string. If there is a tag, like `!!null` it works as expected, which also outputs the tag in the object, which is not ideal since it doesn't round trip the YAML the way that would be expected.

I have some code ready for it, just want to run some additional tests and validate it a little more to make sure it's most likely not going to inadvertently break some consumer of the library.

**Comment by EdwardCooke** [comment]
I have a PR ready with good tests around it to make sure it won't break existing users (in theory). I am going to give the current version another week before putting out a new one.
