### ISSUE TITLE
Schema validation support

### ISSUE THREAD

**Issue by dirtygooback** [aaubry/YamlDotNet#823]
Are there any plans to support schema validation?

**Comment by EdwardCooke** [comment]
Can you describe your use case and what you would expect the library to do in terms of schema validation.

**Comment by dirtygooback** [comment]
I was thinking of something along the lines of how JSON or XML schemas are validated. One would provide a YAML schema similar to the now archived one at [xxx ](https://github.com/spacetelescope/yaml-schema-standard/tree/master/schemas/stsci.edu) and call a Validate method from the YamlDotNet tool. Validate would accept a YAML and a YAML schema and validate if the YAML matches the schema.

**Comment by EdwardCooke** [comment]
I know i personally don’t have the available time to work on something this large right now. If you wanted to work on this, we’re always open to pull requests. I’d want to follow the json schema spec as closely as possible and not deviate from it unless necessary. I’d probably do a different class/interface for the validator due to the complexity. They also serve two different purposes. Let me think about this a little more, but it would be something that I personally couldn’t do right now and would need to be built by the community.

**Comment by dirtygooback** [comment]
Why would you want to follow the schema specification of a different language?

**Comment by EdwardCooke** [comment]
Because yaml and json are very similar and mostly cross compatible. It’s also an existing standard that is widely used and understood. I would rather not reinvent the wheel unless there is some reason to do so, and where there is an existing spec that we can use, not sure we want to do that.

FYI, the repo you linked used the json schema spec as the baseline for that particular project.

**Comment by dirtygooback** [comment]
I, unfortunately, do not share the same viewpoint when it comes to re-using another language specification to validate YAML. It tightly couples the two together. STSCI has the correct idea, base it off of another language because it's similar but don't just steal it verbatim. So if I do decide to work on this then it will be using the STSCI format (or close to it). That way if there is ever a future deviation of the YAML language specification, this will already be setup.  It's a shame, really, that no schema definition exists for "markup" language that is 20+ years old.

**Comment by EdwardCooke** [comment]
I’m not saying steal it. Just use it as the basis and modify where necessary. Exactly what they did in that repo, though it didn’t look like it did any actual validation in there, just transformed the json schema spec file and made it a yaml file. I haven’t had much time to really dig into this due to other obligations and work. It’s just my initial thoughts.

**Comment by dirtygooback** [comment]
I'll try and throw something together and see is anything comes of it.

**Comment by EdwardCooke** [comment]
Were you able to do anything with this request? Or can I close it?

**Comment by dirtygooback** [comment]
apologies, I am not doner with it. Feel free to close this out and I will submit a PR when I am further along :)
