### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [aaubry/YamlDotNet#850]
Maybe You will be interested in hosting API Explorer online:
https://www.robiniadocs.com/d/yamldotnet/api/YamlDotNet.Core.html

This is ready-to-go, so above link can be added to README.md for other people to see it.
Or using ready shields.io badge:

[![Static Badge](https://img.shields.io/badge/API%20Docs-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/yamldotnet/api/YamlDotNet.Core.html)

```
[![Static Badge](https://img.shields.io/badge/API%20Docs-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/yamldotnet/api/YamlDotNet.Core.html)
```

https://github.com/NeuroXiq/RobiniaDocs

Regards
NeuroXiq

**Comment by EdwardCooke** [comment]
Interesting, I was thinking of doing something very similar (with docfx as well) soon that would be managed by us  with logos and previous versions and such. Just haven't had much time to do it just yet. Since I already have plans of doing this in an official capacity, I'm going to go ahead and close. Thanks for showing interest though it really is appreciated.
