### ISSUE TITLE
Implement option to write sequences out in flow stlye for only certain fields with primitive arrays

### ISSUE THREAD

**Issue by szahn** [aaubry/YamlDotNet#9]
Sequences are currently being written out as blocks. There should be a public variable in the emitter to set the style to flow on certain fields that hold arrays with primitive values.

See http://yaml.org/spec/1.0/#id2564419

**Comment by loudenvier** [comment]
Is flow style for sequences implemented in the current version? I was using YamlDotNet to dump objects but since I've got a few relatively large byte arrays it is making the dump next to unreadable (which defeats the purpose of Yaml :-) ) I was expecting something in SerializerOptions but didn't find anything, then stumbled on this issue. Any news?

**Comment by mathiassiig** [comment]
Is it there yet?

**Comment by mathiassiig** [comment]
Anyone stumbling upon this, I was able to do it with this fork https://github.com/xoofx/SharpYaml

You then apply this attribute on the fields you want to have a different style:
[SharpYaml.Serialization.YamlStyle(YamlStyle.Flow)]

**Comment by samsmithnz** [comment]
@mathiassiig Is it possible to submit this as a pull request to the main branch? Especially with GitHub Actions YAML using this in places, it would be useful to have this functionality.

**Comment by EdwardCooke** [comment]
This issue appears to be abandoned, I'm going to close it. I believe this is already implemented.

**Comment by cmeeren** [comment]
I can't see any information in this issue or linked issues that this is implemented. Is it, and if so, how can it be accomplished?

Also, is there any way to set max line length for flow-style arrays (making them break when the max length has been reached)?

**Comment by EdwardCooke** [comment]
We don’t have a way of doing that in yamldotnet that I’m aware of. We’re very grateful for pull requests if you want to create one.

**Comment by cmeeren** [comment]
Thanks. Unfortunately swamped. I found a (hacky?) workaround: In `Visit(YamlSequenceNode sequence)`, check the `NodeType` of the items of the sequence and check if they are `YamlNodeType.Scalar`.

In any case, it seems this issue was closed erroneously then. You may consider opening it, for clarity.

**Comment by EdwardCooke** [comment]
I closed because there was no comment for 3 years.
